version: '3.9'

services:
  webserver:
    build: simple_project
    ports:
      - "8888:80"
    depends_on:
      - database
    volumes:
      - ./data:/data

  database:
    image: postgres
    environment:
      POSTGRES_USER: petr
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: moskovskikh
    volumes:
      - ./pgdata:/var/lib/postgresql/data
